# Environment: Development configs

# Server configs
server:
  port: ${PORT:1406}
  servlet:
    context-path: /flycommerce
  error:
    include-message: always
    include-binding-errors: always

# Spring configs
spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/${DB_NAME:flydb}?autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
    username: ${DB_USER:jcgfdev}
    password: ${DB_PASS:Ju@n1406!}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  data:
    mongodb:
      repositories:
        enabled: false
      host: ${MONGO_HOST:localhost}
      port: ${MONGO_PORT:27017}
      database: ${MONGO_DB:flyorders}
  kafka:
    bootstrap-servers: ${KAFKA_BROKER:kafkafly:9092}
    consumer:
      group-id: flycommerce-group
      auto-offset-reset: earliest
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

# JWT configs
jwt:
  secret: ${JWT_SECRET:C0nden@!to.Ju@n1406!fcf22006743ff01f5241b244f5063c18638}
  expiration: ${JWT_EXPIRATION:3600000}

# CORS config
configs:
  origins:
    - http://localhost:4200
    - https://localhost:4200
    - http://localhost:8080
    - https://localhost:8080
    - http://localhost:5173
    - https://localhost:5173
  methods:
    - GET
    - POST
    - PUT
    - DELETE
    - OPTIONS
  header:
    - Access-Control-Allow-Headers
    - Content-Type
    - Authorization
    - Access-Control-Allow-Origin
    - Access-Control-Allow-Credentials

# OpenAPI / Swagger config
springdoc:
  api-docs:
    path: /api-docs

# Log config
logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
