# Etapa 1: Build con Maven y Java 21
FROM maven:3.9.4-amazoncorretto-21 AS builder

WORKDIR /app

COPY pom.xml .
COPY src ./src

# Build sin tests para la imagen
RUN mvn clean package -DskipTests

# Etapa 2: Runtime con Amazon Corretto 21
FROM amazoncorretto:21-alpine3.18

ENV SPRING_PROFILES_ACTIVE=dev

WORKDIR /app

COPY --from=builder /app/target/flycommerce-*.jar app.jar

ENTRYPOINT ["java", "-jar", "app.jar"]